#!/usr/bin/env groovy
pipeline {
      agent any
      stages {
          stage('Build') {
              agent {
                  label { image 'maven' }
              }
              steps {
                 sh "mvn package -Dmaven.test.skip=true"
              }
         }
      }
}